import { MonthData } from "./types";

type CityMonthly = Record<string, MonthData>;

const MONTHS = ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"];

function m(weather: number, crowds: MonthData["crowds"], costLevel: MonthData["costLevel"], note?: string): MonthData {
  return { weather, crowds, costLevel, note };
}

export const MONTHLY_DATA: Record<string, CityMonthly> = {
  bangkok: {
    Jan: m(8, "High",   "Normal",  "Peak season — sunny and dry"),
    Feb: m(8, "High",   "Normal",  "Still peak — best weather"),
    Mar: m(6, "Medium", "Normal",  "Getting hot"),
    Apr: m(4, "Low",    "Normal",  "Very hot — Songkran festival"),
    May: m(5, "Low",    "Cheaper", "Rains begin"),
    Jun: m(5, "Low",    "Cheaper", "Wet season"),
    Jul: m(5, "Low",    "Cheaper", "Wet season"),
    Aug: m(5, "Low",    "Cheaper", "Wet season"),
    Sep: m(4, "Low",    "Cheaper", "Wettest month"),
    Oct: m(5, "Low",    "Cheaper", "Rains easing"),
    Nov: m(7, "Medium", "Normal",  "Dry season returns"),
    Dec: m(8, "High",   "Pricier", "Christmas & New Year crowds"),
  },
  tokyo: {
    Jan: m(5, "Medium", "Normal",  "Cold but clear"),
    Feb: m(5, "Low",    "Normal",  "Coldest month"),
    Mar: m(7, "High",   "Pricier", "Cherry blossom season"),
    Apr: m(8, "High",   "Pricier", "Peak cherry blossoms"),
    May: m(8, "Medium", "Normal",  "Pleasant spring"),
    Jun: m(6, "Low",    "Normal",  "Rainy season"),
    Jul: m(5, "Medium", "Normal",  "Hot and humid"),
    Aug: m(5, "High",   "Normal",  "Summer festivals"),
    Sep: m(6, "Medium", "Normal",  "Typhoon risk"),
    Oct: m(8, "High",   "Pricier", "Autumn foliage peak"),
    Nov: m(7, "Medium", "Normal",  "Cool and comfortable"),
    Dec: m(5, "Medium", "Normal",  "Cold, illumination events"),
  },
  lisbon: {
    Jan: m(6, "Low",    "Cheaper", "Mild winter, few tourists"),
    Feb: m(6, "Low",    "Cheaper", "Quiet and affordable"),
    Mar: m(7, "Low",    "Cheaper", "Warming up"),
    Apr: m(8, "Medium", "Normal",  "Great spring weather"),
    May: m(8, "Medium", "Normal",  "Long sunny days"),
    Jun: m(9, "High",   "Normal",  "Festivals and warm evenings"),
    Jul: m(9, "High",   "Pricier", "Peak summer"),
    Aug: m(9, "High",   "Pricier", "Very busy, very hot"),
    Sep: m(8, "Medium", "Normal",  "Warm, fewer crowds"),
    Oct: m(7, "Low",    "Normal",  "Lovely autumn"),
    Nov: m(6, "Low",    "Cheaper", "Cooler, rainy spells"),
    Dec: m(6, "Low",    "Cheaper", "Quiet Christmas"),
  },
  bali: {
    Jan: m(6, "Medium", "Normal",  "Wet season"),
    Feb: m(5, "Low",    "Cheaper", "Wettest month"),
    Mar: m(6, "Low",    "Cheaper", "Rains tapering off"),
    Apr: m(7, "Medium", "Normal",  "Transitional — good value"),
    May: m(8, "Medium", "Normal",  "Dry season begins"),
    Jun: m(9, "High",   "Normal",  "Dry and breezy — best months"),
    Jul: m(9, "High",   "Pricier", "Peak season"),
    Aug: m(9, "High",   "Pricier", "Very busy"),
    Sep: m(8, "Medium", "Normal",  "Still dry, thinning crowds"),
    Oct: m(7, "Medium", "Normal",  "Transitional"),
    Nov: m(6, "Low",    "Cheaper", "Wet season returns"),
    Dec: m(6, "Medium", "Normal",  "Festive but wet"),
  },
  barcelona: {
    Jan: m(6, "Low",    "Cheaper", "Cool, very quiet"),
    Feb: m(6, "Low",    "Cheaper", "Quiet and cheap"),
    Mar: m(7, "Low",    "Normal",  "Warming up"),
    Apr: m(7, "Medium", "Normal",  "Easter crowds possible"),
    May: m(8, "Medium", "Normal",  "Perfect weather"),
    Jun: m(9, "High",   "Pricier", "Primes begin"),
    Jul: m(9, "High",   "Pricier", "Peak summer — beaches packed"),
    Aug: m(9, "High",   "Pricier", "Very busy, very hot"),
    Sep: m(8, "Medium", "Normal",  "Warm and less crowded"),
    Oct: m(7, "Low",    "Normal",  "Pleasant autumn"),
    Nov: m(6, "Low",    "Cheaper", "Cooling down"),
    Dec: m(6, "Low",    "Normal",  "Festive lights"),
  },
  "mexico-city": {
    Jan: m(7, "Low",    "Normal",  "Dry and mild"),
    Feb: m(7, "Low",    "Normal",  "Pleasant dry season"),
    Mar: m(8, "Medium", "Normal",  "Warm and clear"),
    Apr: m(8, "Medium", "Normal",  "Best weather"),
    May: m(7, "Medium", "Normal",  "Rains start late month"),
    Jun: m(6, "Low",    "Cheaper", "Wet season"),
    Jul: m(6, "Low",    "Cheaper", "Wet but manageable"),
    Aug: m(6, "Low",    "Cheaper", "Wet season"),
    Sep: m(5, "Low",    "Cheaper", "Wettest month"),
    Oct: m(8, "Medium", "Normal",  "Clear skies return"),
    Nov: m(8, "Medium", "Normal",  "Día de los Muertos"),
    Dec: m(7, "High",   "Pricier", "Christmas festivities"),
  },
  "cape-town": {
    Jan: m(9, "High",   "Pricier", "Peak summer — beaches perfect"),
    Feb: m(9, "High",   "Pricier", "Excellent beach weather"),
    Mar: m(8, "Medium", "Normal",  "Still warm, fewer crowds"),
    Apr: m(7, "Low",    "Normal",  "Autumn starts"),
    May: m(6, "Low",    "Cheaper", "Cooler, rainy season starts"),
    Jun: m(5, "Low",    "Cheaper", "Winter — rainy and cool"),
    Jul: m(5, "Low",    "Cheaper", "Quietest month"),
    Aug: m(5, "Low",    "Cheaper", "Whale watching season"),
    Sep: m(6, "Low",    "Normal",  "Spring wildflowers"),
    Oct: m(7, "Medium", "Normal",  "Warming up"),
    Nov: m(8, "Medium", "Normal",  "Pre-peak sweet spot"),
    Dec: m(9, "High",   "Pricier", "Festive season peak"),
  },
  "new-york": {
    Jan: m(4, "Medium", "Cheaper", "Cold but iconic winter"),
    Feb: m(4, "Low",    "Cheaper", "Coldest, least crowded"),
    Mar: m(5, "Low",    "Normal",  "Cold, transitioning"),
    Apr: m(7, "Medium", "Normal",  "Cherry blossoms in Central Park"),
    May: m(8, "Medium", "Normal",  "Perfect spring"),
    Jun: m(8, "High",   "Normal",  "Outdoor everything"),
    Jul: m(7, "High",   "Normal",  "Hot and humid, beaches"),
    Aug: m(7, "High",   "Normal",  "Hot, outdoor concerts"),
    Sep: m(8, "High",   "Pricier", "Best month — Fashion Week"),
    Oct: m(8, "High",   "Pricier", "Fall foliage, perfect weather"),
    Nov: m(6, "Medium", "Normal",  "Thanksgiving energy"),
    Dec: m(4, "High",   "Pricier", "Holiday magic — very busy"),
  },
};

export { MONTHS };
