import { City, Review } from "./types";
import { MONTHLY_DATA } from "./monthly-data";

export const cities: City[] = [
  {
    id: "1",
    slug: "bangkok",
    name: "Bangkok",
    country: "Thailand",
    countryIso: "764",
    region: "Southeast Asia",
    imageUrl: "https://images.unsplash.com/photo-1508009603885-50cf7c579365?w=800&q=80",
    summary: "A chaotic, delicious, endlessly entertaining city where ancient temples meet rooftop bars.",
    whyVisit: "Bangkok rewards every type of traveler. Budget backpackers love the street food and cheap guesthouses; luxury seekers find world-class hotels at half the Western price. The food scene alone justifies the flight.",
    bestAreas: ["Sukhumvit", "Silom", "Khao San Road", "Chatuchak", "Riverside"],
    bestThingsToDo: ["Visit Wat Pho and the Grand Palace", "Explore Chatuchak Weekend Market", "Take a Chao Phraya river cruise", "Eat your way through street food stalls", "Rooftop bar at sunset"],
    bestFor: ["Solo", "Food", "Nightlife", "Backpacking", "Culture"],
    scores: {
      overall: 8.7,
      costValue: 9.2,
      safety: 7.8,
      food: 9.5,
      culture: 8.9,
      nature: 5.5,
      nightlife: 9.0,
      easeOfTravel: 8.2,
    },
    dailyBudget: { budget: 35, midRange: 75, luxury: 180, currency: "USD" },
    budgetBreakdown: { accommodation: 15, food: 10, transport: 5, activities: 8, extras: 7 },
    bestSeason: "Nov–Feb",
    reviewCount: 124,
    anonymousRatingCount: 342,
    commonComplaints: ["Heat and humidity year-round", "Traffic congestion", "Tourist scams near major temples", "Pollution in busy areas"],
    monthlyData: MONTHLY_DATA.bangkok,
  },
  {
    id: "2",
    slug: "tokyo",
    name: "Tokyo",
    country: "Japan",
    countryIso: "392",
    region: "East Asia",
    imageUrl: "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=800&q=80",
    summary: "Hyper-efficient, deeply fascinating, and surprisingly affordable — Tokyo is one of the world's great cities.",
    whyVisit: "Tokyo is endlessly layered. Spend a week here and only scratch the surface. From tiny ramen bars to Michelin-starred restaurants, from quiet temples to neon-drenched neighborhoods, every corner surprises.",
    bestAreas: ["Shinjuku", "Shibuya", "Asakusa", "Harajuku", "Shimokitazawa"],
    bestThingsToDo: ["Walk the Shibuya crossing at night", "Explore Tsukiji outer market", "Day trip to Nikko or Kamakura", "Visit Senso-ji temple", "Ramen at a local neighborhood spot"],
    bestFor: ["Solo", "Couple", "Food", "Culture", "Digital Nomad"],
    scores: {
      overall: 9.2,
      costValue: 7.5,
      safety: 9.8,
      food: 9.7,
      culture: 9.5,
      nature: 6.0,
      nightlife: 8.5,
      easeOfTravel: 9.0,
    },
    dailyBudget: { budget: 80, midRange: 160, luxury: 350, currency: "USD" },
    budgetBreakdown: { accommodation: 35, food: 25, transport: 10, activities: 15, extras: 5 },
    bestSeason: "Mar–May, Sep–Nov",
    reviewCount: 218,
    anonymousRatingCount: 589,
    commonComplaints: ["Expensive accommodation", "Language barrier outside tourist areas", "Small accommodation sizes", "Crowded during holidays"],
    monthlyData: MONTHLY_DATA.tokyo,
  },
  {
    id: "3",
    slug: "lisbon",
    name: "Lisbon",
    country: "Portugal",
    countryIso: "620",
    region: "Europe",
    imageUrl: "https://images.unsplash.com/photo-1555881400-74d7acaacd8b?w=800&q=80",
    summary: "Sun-soaked, hilly, and full of character — Lisbon is Europe's most underrated capital.",
    whyVisit: "Lisbon offers Europe's warmth — literally and figuratively — at prices that feel like 10 years ago. Charming old trams, incredible seafood, and a sunset from a miradouro you won't forget.",
    bestAreas: ["Alfama", "Bairro Alto", "Chiado", "Belém", "LX Factory"],
    bestThingsToDo: ["Ride Tram 28 through Alfama", "Watch fado live", "Visit Torre de Belém", "Day trip to Sintra", "Sunset at Miradouro da Graça"],
    bestFor: ["Couple", "Honeymoon", "Culture", "Food", "Digital Nomad"],
    scores: {
      overall: 8.9,
      costValue: 8.3,
      safety: 9.0,
      food: 8.7,
      culture: 9.1,
      nature: 7.0,
      nightlife: 7.8,
      easeOfTravel: 8.5,
    },
    dailyBudget: { budget: 60, midRange: 120, luxury: 260, currency: "USD" },
    budgetBreakdown: { accommodation: 30, food: 18, transport: 8, activities: 12, extras: 7 },
    bestSeason: "Apr–Jun, Sep–Oct",
    reviewCount: 96,
    anonymousRatingCount: 278,
    commonComplaints: ["Overcrowded in peak summer", "Hilly terrain is tiring", "Rising prices due to tourism", "Limited late-night public transport"],
    monthlyData: MONTHLY_DATA.lisbon,
  },
  {
    id: "4",
    slug: "bali",
    name: "Bali",
    country: "Indonesia",
    countryIso: "360",
    region: "Southeast Asia",
    imageUrl: "https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=800&q=80",
    summary: "Sacred temples, emerald rice terraces, and a wellness culture that draws visitors back year after year.",
    whyVisit: "Bali is one of those rare places that feels spiritual without trying. Even if you're not into yoga retreats, the landscape, food, and people make this an exceptional destination.",
    bestAreas: ["Ubud", "Seminyak", "Canggu", "Uluwatu", "Nusa Dua"],
    bestThingsToDo: ["Watch sunrise at Mount Batur", "Visit Tegallalang rice terraces", "Uluwatu temple at sunset", "Surf at Kuta or Canggu", "Cooking class in Ubud"],
    bestFor: ["Honeymoon", "Couple", "Solo", "Adventure", "Beach", "Nature"],
    scores: {
      overall: 8.5,
      costValue: 8.8,
      safety: 8.0,
      food: 8.2,
      culture: 8.6,
      nature: 9.3,
      nightlife: 7.5,
      easeOfTravel: 7.5,
    },
    dailyBudget: { budget: 40, midRange: 90, luxury: 220, currency: "USD" },
    budgetBreakdown: { accommodation: 20, food: 12, transport: 8, activities: 12, extras: 8 },
    bestSeason: "May–Sep",
    reviewCount: 183,
    anonymousRatingCount: 461,
    commonComplaints: ["Traffic in southern Bali", "Overtourism in popular spots", "Requires transport to get around", "Monsoon season can disrupt plans"],
    monthlyData: MONTHLY_DATA.bali,
  },
  {
    id: "5",
    slug: "barcelona",
    name: "Barcelona",
    country: "Spain",
    countryIso: "724",
    region: "Europe",
    imageUrl: "https://images.unsplash.com/photo-1523531294919-4bcd7c65e216?w=800&q=80",
    summary: "Gaudí's living city — architecture, beaches, tapas, and a nightlife scene that starts at midnight.",
    whyVisit: "Barcelona is a city of contrast: world-famous architecture beside golden beaches, late dinners and even later nights, a metro that covers everything. Few cities pack this much personality.",
    bestAreas: ["Gothic Quarter", "El Born", "Eixample", "Gràcia", "Barceloneta"],
    bestThingsToDo: ["Visit La Sagrada Família", "Walk Las Ramblas early morning", "Explore Park Güell", "Tapas tour in El Born", "Beach day at Barceloneta"],
    bestFor: ["Friends", "Couple", "Culture", "Nightlife", "Beach"],
    scores: {
      overall: 9.0,
      costValue: 7.2,
      safety: 7.5,
      food: 9.0,
      culture: 9.3,
      nature: 7.0,
      nightlife: 9.2,
      easeOfTravel: 8.8,
    },
    dailyBudget: { budget: 70, midRange: 140, luxury: 300, currency: "USD" },
    budgetBreakdown: { accommodation: 35, food: 20, transport: 8, activities: 15, extras: 10 },
    bestSeason: "Apr–Jun, Sep–Oct",
    reviewCount: 142,
    anonymousRatingCount: 402,
    commonComplaints: ["Pickpockets on Las Ramblas", "Expensive compared to other Spanish cities", "Overcrowded tourist sites", "Noise at night in central areas"],
    monthlyData: MONTHLY_DATA.barcelona,
  },
  {
    id: "6",
    slug: "mexico-city",
    name: "Mexico City",
    country: "Mexico",
    countryIso: "484",
    region: "North America",
    imageUrl: "https://images.unsplash.com/photo-1518105779142-d975f22f1b0a?w=800&q=80",
    summary: "One of the world's great food cities, with world-class museums, a vibrant arts scene, and surprising greenery.",
    whyVisit: "Mexico City punches above its weight in almost every category — food, art, architecture, nightlife. It's one of the most culturally rich cities in the Western Hemisphere, and still affordable.",
    bestAreas: ["Roma Norte", "Condesa", "Coyoacán", "Polanco", "Centro Histórico"],
    bestThingsToDo: ["Visit the Frida Kahlo Museum", "Explore Teotihuacán pyramids", "Eat tacos at a local taquería", "Sunday at Chapultepec Park", "Browse the Palacio de Bellas Artes"],
    bestFor: ["Solo", "Food", "Culture", "Friends", "Adventure"],
    scores: {
      overall: 8.6,
      costValue: 8.7,
      safety: 6.8,
      food: 9.6,
      culture: 9.4,
      nature: 6.5,
      nightlife: 8.8,
      easeOfTravel: 7.8,
    },
    dailyBudget: { budget: 45, midRange: 95, luxury: 210, currency: "USD" },
    budgetBreakdown: { accommodation: 20, food: 14, transport: 6, activities: 12, extras: 8 },
    bestSeason: "Mar–May, Oct–Nov",
    reviewCount: 87,
    anonymousRatingCount: 231,
    commonComplaints: ["Air quality on bad days", "Safety concerns in some neighborhoods", "Altitude sickness for new arrivals", "Traffic and sprawl"],
    monthlyData: MONTHLY_DATA["mexico-city"],
  },
  {
    id: "7",
    slug: "cape-town",
    name: "Cape Town",
    country: "South Africa",
    countryIso: "710",
    region: "Africa",
    imageUrl: "https://images.unsplash.com/photo-1580060839134-75a5edca2e99?w=800&q=80",
    summary: "Where mountains meet the ocean — Cape Town is Africa's most visually spectacular city.",
    whyVisit: "The combination of dramatic scenery, excellent food and wine, wildlife nearby, and a vibrant city makes Cape Town almost unfair. Table Mountain alone is worth the trip.",
    bestAreas: ["V&A Waterfront", "De Waterkant", "Gardens", "Sea Point", "Camps Bay"],
    bestThingsToDo: ["Hike or cable car up Table Mountain", "Drive the Cape Peninsula", "Visit Cape Point and Boulder's Beach penguins", "Wine tasting in Stellenbosch", "Sunset at Signal Hill"],
    bestFor: ["Couple", "Adventure", "Nature", "Honeymoon", "Friends"],
    scores: {
      overall: 8.8,
      costValue: 8.0,
      safety: 6.5,
      food: 8.5,
      culture: 8.0,
      nature: 9.5,
      nightlife: 7.8,
      easeOfTravel: 7.0,
    },
    dailyBudget: { budget: 55, midRange: 110, luxury: 250, currency: "USD" },
    budgetBreakdown: { accommodation: 25, food: 16, transport: 10, activities: 15, extras: 9 },
    bestSeason: "Nov–Mar",
    reviewCount: 74,
    anonymousRatingCount: 198,
    commonComplaints: ["Safety concerns in some areas", "Requires a car to explore properly", "Load shedding power outages", "Inequality is visible and confronting"],
    monthlyData: MONTHLY_DATA["cape-town"],
  },
  {
    id: "8",
    slug: "new-york",
    name: "New York City",
    country: "United States",
    countryIso: "840",
    region: "North America",
    imageUrl: "https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?w=800&q=80",
    summary: "The city that never sleeps — dense, electric, expensive, and impossible to fully explore.",
    whyVisit: "New York is a rite of passage. Every neighborhood feels like a different city; the food reflects the world; the energy is unmatched. Expensive, yes — but there's nowhere quite like it.",
    bestAreas: ["Manhattan", "Brooklyn (Williamsburg, DUMBO)", "Queens (Astoria)", "Lower East Side", "West Village"],
    bestThingsToDo: ["Walk the Brooklyn Bridge", "Spend a morning at the Met", "Grab a bagel in the morning", "High Line park stroll", "Eat everything in Queens"],
    bestFor: ["Friends", "Solo", "Culture", "Food", "Nightlife"],
    scores: {
      overall: 8.8,
      costValue: 5.5,
      safety: 7.8,
      food: 9.3,
      culture: 9.6,
      nature: 5.0,
      nightlife: 9.0,
      easeOfTravel: 8.5,
    },
    dailyBudget: { budget: 120, midRange: 250, luxury: 550, currency: "USD" },
    budgetBreakdown: { accommodation: 60, food: 35, transport: 12, activities: 20, extras: 13 },
    bestSeason: "Apr–Jun, Sep–Nov",
    reviewCount: 195,
    anonymousRatingCount: 512,
    commonComplaints: ["Very expensive", "Subway reliability", "Noise and crowding", "Extreme summer heat and winter cold"],
    monthlyData: MONTHLY_DATA["new-york"],
  },
];

export const reviews: Review[] = [
  {
    id: "r1",
    cityId: "1",
    authorName: "Sarah M.",
    travelStyle: "Solo",
    budgetCategory: "budget",
    monthVisited: "January 2025",
    overallRating: 9,
    writtenReview: "Bangkok blew me away. I was nervous traveling solo but it's incredibly easy to get around. The street food is unreal — I ate pad see ew and mango sticky rice every single day. Grab is cheap, BTS skytrain is efficient, and everyone is genuinely friendly.",
    pros: ["Incredible food at every price point", "Very affordable", "Easy to meet other travelers"],
    cons: ["Heat in March–May is brutal", "Temple scams near Wat Pho"],
    createdAt: "2025-01-20",
  },
  {
    id: "r2",
    cityId: "1",
    authorName: "James T.",
    travelStyle: "Couple",
    budgetCategory: "midRange",
    monthVisited: "November 2024",
    overallRating: 8,
    writtenReview: "Great city for a couple — we split our time between the cultural sites and some rooftop bar nights. The Grand Palace is genuinely impressive. Would avoid peak tourist season if possible.",
    pros: ["Great mix of culture and nightlife", "Excellent mid-range hotel options", "River taxi is fun and useful"],
    cons: ["Traffic is genuinely terrible", "Some areas feel very touristy"],
    createdAt: "2024-11-15",
  },
  {
    id: "r3",
    cityId: "2",
    authorName: "Yuki A.",
    travelStyle: "Solo",
    budgetCategory: "midRange",
    monthVisited: "April 2025",
    overallRating: 10,
    writtenReview: "Tokyo is the greatest city I've ever visited. I spent 12 days and could have stayed 12 more. The food is flawless at every level — ¥600 ramen that beats anything back home. Safest I've ever felt in a major city. Already planning to return.",
    pros: ["Safest big city in the world", "Food is extraordinary", "Clean, efficient, organized"],
    cons: ["Can be expensive for accommodation", "English not always available outside tourist zones"],
    createdAt: "2025-04-10",
  },
];
